### ISSUE TITLE
missing export?

### ISSUE THREAD

**Issue by StCyr** [parys-github/vue-masonry-gallery#1]
Hello, 

I'm trying to use your component but `import VueMasonryGallery from "vue-masonry-gallery";` fails with: `Module not found: Error: Can't resolve 'vue-masonry-gallery' in '/root/social/src/components'`

I guess you're missing an export somewhere.

Regards,

Cyrille

**Comment by parys-github** [comment]
Thanks Cyrille for your feedback. 
Unfortunately, some of the libraries I used are already deprecated. In addition, the idea of building a template with pug's is not the best solution with Vue as well. Actually, 
I am gonna update the whole project based on Vuetify soon :-)

**Comment by SohrabZ** [comment]
@StCyr this will fix the issue:
```js
import VueMasonryGallery from 'vue-masonry-gallery/vendor/VueMasonryGallery/VueMasonryGallery'
```
